algoritmo "Exercício 007"
// Descrição   : Ler um número real e mostrar seu dobro e a terça parte.
// Autor(a)    : Kauã Poças Freire
// Data atual  : 25/04/2025

var

    n, dobro, terc: real

inicio

    escreva ("Digite um número: ")
    leia (n)

    dobro <- n * 2
    terc <- n / 3

    escreval ("O dobro de " + n + " é " + dobro)
    escreval ("A terça parte de " + n + " é " + terc:4:2)

fimalgoritmo