algoritmo "Exercício 003"
// Descrição   : Ler nome e salário de um funcionário e exibir mensagem com esses dados.
// Autor(a)    : Kauã Poças Freire
// Data atual  : 25/04/2025

var

nome: caractere
salario: real

inicio

escreva ("Nome do Funcionário: ")
leia (nome)
escreva ("Salário: ")
leia (salario)

escreval ("O funcionário " + nome + " tem um salário de R$" + salario + " em Junho.")


fimalgoritmo