algoritmo "Exercício 004"
// Descrição   : Ler dois números inteiros e mostrar a soma entre eles.
// Autor(a)    : Kauã Poças Freire
// Data atual  : 25/04/2025

var

    n1, n2, soma: inteiro

inicio

    escreva ("Digite um valor: ")
    leia (n1)
    escreva ("Digite outro valor: ")
    leia (n2)

    soma <- n1 + n2

    escreval ("A soma entre " + n1 + " e " + n2 + " é igual a " + soma + ".")

fimalgoritmo