algoritmo "Exercício 011"
// Descrição   : Calcular o valor de Delta de uma equação do 2º grau.
// Autor(a)    : Kauã Poças Freire
// Data atual  : 27/04/2025
var

    A, B, C, delta: real

inicio

    escreva ("Digite o valor de A: ")
    leia (A)
    escreva ("Digite o valor de B: ")
    leia (B)
    escreva ("Digite o valor de C: ")
    leia (C)

    delta <- B^2 - 4 * A * C

    escreval ("O valor de delta é: ", delta)

fimalgoritmo